version: "3.5"
services:
  app:
    # image: artalk/artalk-go:2.9.1
    image: registry.cn-shenzhen.aliyuncs.com/terwer/dm:artalk-go-2.9.1
    container_name: artalk
    ports:
      - "8003:23366"
    volumes:
      - ./artalk/data:/data
      - ./artalk/ssl/certs/cert.pem:/etc/ssl/certs/cert.pem
      - ./artalk/ssl/certs/cert.key:/etc/ssl/certs/cert.key
