version: "3.5"
services:
  artalk:
    image: terwer/artalk:2.1
    container_name: artalk
    build:
      context: ./
      dockerfile: ./artalk/Dockerfile
    ports:
      - 8003:23366
    volumes:
      - ./artalk/data:/data
      - ./artalk/ssl/certs/cert.pem:/etc/ssl/certs/cert.pem
      - ./artalk/ssl/certs/cert.key:/etc/ssl/certs/cert.key
#  后续打算弄一个统一的nginx反代，443作为统一的入口，不被特定模块占用，因此，本项目的nginx代理废弃
#  artalk-nginx:
#    image: terwer/artalk-nginx:1.15.9
#    container_name: artalk-nginx
#    build:
#      context: ./
#      dockerfile: ./artalk-nginx/Dockerfile
#    ports:
#      - "8004:80"
#      - "444:443"
#    volumes:
#      - ./artalk-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./artalk-nginx/log:/var/log/nginx
#      - ./artalk-nginx/ssl/certs/cert.pem:/etc/ssl/certs/cert.pem
#      - ./artalk-nginx/ssl/certs/cert.key:/etc/ssl/certs/cert.key
#    restart: "no"