version: "3.5"
services:
  artalk:
    image: terwer/artalk:2.1
    container_name: artalk
    build:
      context: ./
      dockerfile: ./artalk/Dockerfile
    ports:
      - 8003:23366
    volumes:
      - ./artalk/data:/data
  artalk-nginx:
    image: terwer/artalk-nginx:1.15.9
    container_name: artalk-nginx
    build:
      context: ./
      dockerfile: ./artalk-nginx/Dockerfile
    ports:
      - "8004:80"
      - "443:443"
    volumes:
      - ./artalk-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./artalk-nginx/log:/var/log/nginx
      - ./artalk-nginx/ssl/certs/cert.pem:/etc/ssl/certs/cert.pem
      - ./artalk-nginx/ssl/certs/cert.key:/etc/ssl/certs/cert.key
    restart: "no"