version: "3.5"
services:
  artalk:
    container_name: artalk
    image: artalk/artalk-go
    ports:
      - 8003:23366
    volumes:
      - ./data:/data
  artalk-nginx:
    image: nginx:1.15.9-alpine
    container_name: artalk-nginx
    ports:
      - "8004:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    restart: "no"